### PR TITLE
refactor: fix checkjs error

### LINKED ISSUE #5: [CheckJs Error]: when package.json not found, should return an object with `sha` undefined
https://github.com/octoherd/script-setup-renovate/blob/7ddff65634469652e31ba9c926e57323e447a4dc/script.js#L41

To avoid this
image

### PR DESCRIPTION
**Pull request by oscard0m**
Fix #5

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Kind of an odd error, but okay, if it makes `tsc` happy so be it 🤷🏼

**Comment by oscard0m** [comment]
> Kind of an odd error, but okay, if it makes `tsc` happy so be it 🤷🏼

I thought exactly the same. In my mind that code should be valid since `undefined` fits under `any`

File: script.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ export async function script(octokit, repository, options) {
         };
       },
       (error) => {
-        if (error.status === 404) return { pkg: false };
+        if (error.status === 404) return { pkg: false, sha: undefined };
```
Comment (gr2m) [inline script.js:41]: Actually can you add a comment to explain why we did this? Maybe it will become obsolete in future. Maybe sth like this

```js
         // return { sha } to make TypeScript check happy
         if (error.status === 404) return { pkg: false, sha: undefined };
```

Comment (oscard0m) [reply script.js:41]: I was thinking... Should this be an issue to TypeScript and we should use `//@ts-expect-error` here? @gr2m (adding the comment you suggested in the meantime)

Comment (gr2m) [reply script.js:41]: yes I would appreciate if you could check in with the TypeScript folks whether this is a bug or expected behavior. 

Actually using `// @ts-expect-error` is a good idea, it's more elegant, and I think TypeScript will complain once there no longer is an error. So maybe do this?

```js
         // @ts-expect-error expects { sha} to be present (see #6)
         if (error.status === 404) return { pkg: false };
```

Comment (oscard0m) [reply script.js:41]: https://github.com/octoherd/script-setup-renovate/pull/10
